modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
[[mods]]
modId="horsepouch"
version="${file.jarVersion}"
displayName="Horse Pouch Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/horsepouch"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Horse Pouch Mod.'
[[dependencies.horsepouch]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horsepouch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
